### ISSUE TITLE
Decide what to do with blockquotes

### ISSUE THREAD

**Issue by iMrDJAi** [dobidi/markdown-it-bidi#16]
Blockquotes are exceptional, we need to define exactly how they should behave with bidirectional text.

Usually, developers add extra CSS to give blockquotes that border on the left, but when the text direction is right to left, the border should be on the right instead, and that looks problematic 🤔. Thankfully, we don't have to write a script that handles that for us 😌! There is a pure CSS solution that makes the border follow the direction of the first strong character: `border-inline-start`!

However, the current design of the plugin prevents `border-inline-start` from working as we give every block element the dir attribute. Keep in mind that the blockquote element isn't a direct parent to the text, instead, there is a paragraph element that contains the text inside, and as it also has `dir="auto"`, the text is isolated from the blockquote causing the CSS trick to be unfunctional.

We have multiple options and we need to decide which one to choose (suggestions are welcome):

Markdown:
```md
> عربية1 عربية2 English عربية3 عربية4
>
> > عربية1 عربية2 English عربية3 عربية4 
>
> > English1 English2 عربية English3 English4
>
> English1 English2 عربية English3 English4
```

<ins>Option 1:</ins> No `dir="auto"` for the first child of the blockquote element:

![image](https://user-images.githubusercontent.com/42304709/151843810-9eb8e27b-361b-4f57-aa8e-c55a429ab45d.png)

```html
<blockquote dir="auto">
  <p>عربية1 عربية2 English عربية3 عربية4</p>
  <blockquote dir="auto">
    <p>عربية1 عربية2 English عربية3 عربية4</p>
  </blockquote>
  <blockquote dir="auto">
    <p>English1 English2 عربية English3 English4</p>
  </blockquote>
  <p dir="auto">English1 English2 عربية English3 English4</p>
</blockquote>
```

<ins>Option 2:</ins> No `dir="auto"` for every non-blockquote element (e.g. p, table...):

![image](https://user-images.githubusercontent.com/42304709/151862095-e460b97e-0386-454f-887e-a1b224f6bc91.png)

```html
<blockquote dir="auto">
  <p>عربية1 عربية2 English عربية3 عربية4</p>
  <blockquote dir="auto">
    <p>عربية1 عربية2 English عربية3 عربية4</p>
  </blockquote>
  <blockquote dir="auto">
    <p>English1 English2 عربية English3 English4</p>
  </blockquote>
  <p>English1 English2 عربية English3 English4</p>
</blockquote>
```

<ins>Option 3:</ins> No `dir="auto"` for every nested element (**Gitlab Approach**):

![image](https://user-images.githubusercontent.com/42304709/151862485-657a0a9b-4e7b-491d-b033-bd356deb0d7a.png)

```html
<blockquote dir="auto">
  <p>عربية1 عربية2 English عربية3 عربية4</p>
  <blockquote>
    <p>عربية1 عربية2 English عربية3 عربية4</p>
  </blockquote>
  <blockquote>
    <p>English1 English2 عربية English3 English4</p>
  </blockquote>
  <p>English1 English2 عربية English3 English4</p>
</blockquote>
```

**Edit:** Here is the CSS I used:

```css
blockquote {
  border-inline-start: .25em solid #bbbbbb;
  padding: 0 .25em;
}
```

**Edit 2:** (Just for reference)

<ins>Option 4:</ins> No `dir="auto"` for blockquote elements (**Github Approach**):

> This approach has one bug: The blockquote element itself doesn't get any direction based on its content. there is one workaround which is to give the style to child elements of a blockquote which results in horrible outcomes with lists and tables.

**Comment by ahangarha** [comment]
I think we need to make a list of real use cases.

I think one solution would be to add `dir="auto"` to `p`. Then in css we can style `blockquote > p` for border, background or any other specific styles needed.

**Comment by iMrDJAi** [comment]
@ahangarha What I'm not sure about is whether is it okay to have nested blockquotes or paragraphs taking the opposite direction of the parent blockquote or not.

**Comment by ahangarha** [comment]
Is there any real use case for nesting blockquote? I am not sure. This is why I want to explore real use cases. And let me emphasis that I am not pushing to get into conclusion. If there be no real use cace of nesting blockquotes, then I think my proposal works perfectly.

**Comment by iMrDJAi** [comment]
> Is there any real use case for nesting blockquote? 

@ahangarha Nope, not really. 😅

But the fact they are supported by the CommonMark spec is enough reason to consider doing something about them.

**Comment by ahangarha** [comment]
Then lets make a list of such cases and see what we expect and what we get from our code. My suggestion should work in those cases I assume but we need to check it in practice and with multiple cases.

**Comment by ahangarha** [comment]
My suggestion is to forget about markdown and html and just make a list of 5 different scenarios in which we might have complex nested quotation. Then for each, we just draw visual expectations. This way, we can start making some guidelines and then some test. This way only we can write code in meaningful way.

I will try to make such list by Saturday night.

**Comment by ahangarha** [comment]
As per our discussion, we have three proposals:

1. **Gitlab Approach:** Only give `dir="auto"` to the blockquote element and not any child elements in it.
    This approach has one bug: all the content follows the direction of the first element in the blockquote 
2. **Github Approach:** Don't give `dir="auto"` to the blockquote but to its child the way we do out of blockquote
    This approach has one bug: The blockquote element itself doens't get any direction based on its content
3. **iMrDJAi Approach:** Add `dir="auto"` to all block elements except first child of of another block element
    This approach has one issue: it breaks its general rule of applying `dir="auto"` to all block elements.

In terms of result, only the 3rd approach produce desirable result.

**Comment by iMrDJAi** [comment]
@ahangarha As you said before:

> Appearance of the text within blockquote should be as close as possible to the original text.

The goal is when you quote existing bidirectional content, the directions should remain the same, I confirm that in terms of result, the 3rd approach is the best, and all other proposals cannot achieve that.

We need to define the spec, and in order to do that we have to conclude a generic rule based on what the 3rd approach solves, this rule should not only apply to blockquotes, but to all other block elements (e.g. tables) too.

Let's get back to the roots of our issue, adding `dir="auto"` to an element simply applies the CSS rule: `unicode-bidi: isolate;` to it, this rule does what it says, it isolates the content of the element from the parents (not necessarily the direct parent element).

In other words, if a parent element relies on the text content of a child element having `dir="auto"` (not necessarily a direct child element) to determine its direction, it won't be able to do that.

From that, we need to ensure that no element between that parent element, and the child element used to determine its direction, in the nesting chain, has the dir attribute set to `auto`.

So, our rule is:
- __Definitions__:
    - __Parent element__: a block element having an automatic direction (`dir="auto"`)`.

    - __Child element__: the very first nested element found inside the **parent element** that is supposed to contain text.

- __Generic rule__: No element between the **parent element** and the **child element** in the **chain of nested elements** may have the dir attribute set to `auto`.

**Comment by ahangarha** [comment]
@iMrDJAi 
Let's share the results in every issue.
