### ISSUE TITLE
Direction of block quotes is reversed

### ISSUE THREAD

**Issue by h-shams** [dobidi/markdown-it-bidi#26]
Hi,
Block quotes in markdown will be transformed like this by  `markdown-it` and `markdown-it-bidi`.
```markdown
> یک متن فارسی
```
``` HTML
<blockquote dir="auto">
    <p dir="auto">یک متن فارسی</p>
</blockquote>
```
If you open developer tools in the browser and inspect the `<blockqoute>` element, its `direction` property (which can be seen in the "computed" section) is set to `ltr` instead of `rtl` although its content is in Farsi. If you remove `dir="auto"` attribute of the `<p>` element inside the `<blockqoute>`, the value of the `direction` property of the `<blockqoute>` will be `rtl`. By doing this, we will be able to use CSS to change the style of `<blockqoute>` based on the direction of its content.

Is it reasonable to not add `dir="auto"` attribute to the `<p>` element inside the `<blockqoute>`?

**Comment by ahangarha** [comment]
Thanks for opening this issue.

We need a new release with slight change in our algorithm to fix such issues in nested elements.

Please keep pinging me if you see no update. Do not hesitate at all.

**Comment by h-shams** [comment]
I'm willing to contribute to this if it is possible. If it's OK with you, let me know so I can share my solution, and if it seems reasonable, then I can implement it.

**Comment by ahangarha** [comment]
That would be great.

You may follow the algorithm implemented in [bidify](https://github.com/dobidi/bidify-rb) project (though it is in Ruby language).
Basically, we should avoid applying `dir="auto"` to the first nested element with `dir="auto"`.

Let me know if you need anything.

For now, I assign this issue to you for clarity purpose.

**Comment by ahangarha** [comment]
Version 0.2.0 released with these changes.

Thanks again for your contribution.
